from rosbook
run apt-get install -y ros-kinetic-ivcon ros-kinetic-convex-decomposition
run apt-get install -y libgflags-dev
run mkdir /moveit_ws 
run mkdir /moveit_ws/src
run ["/bin/bash","-c","source /opt/ros/kinetic/setup.bash;cd /moveit_ws/src && catkin_init_workspace"]
workdir /moveit_ws/src
#run git clone https://github.com/davetcoleman/pr2_moveit_config.git -o pr2_moveit_config

run git clone https://github.com/ros-planning/moveit_tutorials.git -o moveit_tutorials 
run git clone https://github.com/PR2/pr2_common.git -b kinetic-devel -o  pr2_common
run git clone https://github.com/davetcoleman/pr2_moveit_config.git  -o  pr2_moveit_config
run git clone https://github.com/shaun-edwards/prettyprint -o prettyprint
#add  moveit_simple_grasps /ros_book_ws/src/moveit_simple_grasps
#add  effective_robotics_programming_with_ros /ros_book_ws/src/effective_robotics_programming_with_ros
#run ["/bin/bash","-c","source /opt/ros/kinetic/setup.bash;cd /ros_book_ws/ && catkin_make"]
#add  effective_robotics_programming_with_ros /ros_book_ws/src/effective_robotics_programming_with_ros
#run ["/bin/bash","-c","source /opt/ros/kinetic/setup.bash;cd /ros_book_ws/ && catkin_make"]
