git clone https://github.com/ros-industrial/abb_experimental
git clone https://github.com/kbehouse/abb_moveit
git clone https://github.com/andreasBihlmaier/ahbstring
git clone https://github.com/JoshMarino/baxter_dual_arm_manipulation
git clone https://github.com/catkin/catkin_simple
git clone https://github.com/Dhivin/IRB-1600
git clone https://github.com/davetcoleman/moveit_cartesian_controller
git clone https://github.com/ros-planning/moveit_tutorials.git
git clone https://github.com/PR2/pr2_common.git
git clone https://github.com/davetcoleman/pr2_moveit_config.git
git clone https://github.com/shaun-edwards/prettyprint
git clone https://github.com/davetcoleman/ros_control_boilerplate
git clone https://github.com/warp1337/rosleapmotion.git
git clone https://github.com/davetcoleman/rosparam_shortcuts
git clone https://github.com/carlosjoserg/rrbot
git clone https://github.com/sastrarobotics/sr_scara_hx_ros
git clone https://github.com/yangliu28/two_scara_collaboration
git clone https://github.com/ros-industrial/universal_robot.git
git clone https://github.com/mehdish89/ur5_manipulation
git clone https://github.com/andreasBihlmaier/ur5_moveit_kinematics
git clone https://github.com/yupos0221/ur_moveit_planner
