git clone https://github.com/Dhivin/5-DOF-ARM-IN-ROS
git clone https://github.com/vanadiumlabs/arbotix_ros
git clone https://github.com/jmichiels/arm
git clone https://github.com/ManMan88/arm_quickbot
git clone https://github.com/nxdefiant/arm_ros_conn
git clone https://github.com/orsalmon/bgumodo_arm
git clone https://github.com/xaedes/canopen_301_402
git clone https://github.com/davetcoleman/clam_rosbuild
git clone https://github.com/ferasboulala/five_dof_robot_arm
git clone https://github.com/jessetham/Grabby-McArmface
git clone https://github.com/Dhivin/Husky-with-custom-arm
git clone https://github.com/jesseweisberg/moveo_ros
git clone https://github.com/RobotnikAutomation/phantomx_reactor_arm
git clone https://github.com/rst-tu-dortmund/pxpincher_ros
git clone https://github.com/GT-RAIL/rail_manipulation_msgs
git clone https://github.com/udacity/RoboND-Kinematics-Project
git clone https://github.com/hamzamerzic/ros-threeseg
git clone https://github.com/oroca/rosbook_robot_arm
git clone https://github.com/byeongkyu/safe_arm
git clone https://github.com/wjwwood/serial_utils
git clone https://github.com/udacity/simple_arm_01
git clone https://github.com/RIVeR-Lab/wpi_jaco
